import 'dart:io';
import '../generated/protocol.dart';

class ArchitectureEvent {
  final String message;
  final String level;
  final double progress;
  final bool isError;

  ArchitectureEvent({
    required this.message,
    this.level = 'info',
    this.progress = 0.0,
    this.isError = false,
  });
}

class ArchitectureGenerator {
  Stream<ArchitectureEvent> generate(ProjectConfig config) async* {
    yield ArchitectureEvent(message: 'Scaffolding architecture structure...', progress: 0.1);
    
    final projectId = config.projectId ?? 'unknown_project';
    final projectDir = Directory('/tmp/flutterforge/$projectId');
    
    // Default to clean_bloc if null
    final pattern = config.architecture?.pattern ?? 'clean_architecture';
    final stateMgmt = config.architecture?.stateManagement ?? 'bloc';
    final templateSet = '${pattern}_$stateMgmt';
    
    yield ArchitectureEvent(message: 'Using template set: $templateSet', progress: 0.2);

    // Create base directories
    final dirsToCreate = [
      'lib/core/di',
      'lib/core/env',
      'lib/core/network',
      'lib/core/router',
      'lib/core/storage',
      'lib/core/theme',
      'lib/features',
      'lib/shared/widgets',
    ];

    for (int i = 0; i < dirsToCreate.length; i++) {
      final dir = dirsToCreate[i];
      await Directory('${projectDir.path}/$dir').create(recursive: true);
      yield ArchitectureEvent(message: 'Created $dir', progress: 0.2 + (0.1 * (i / dirsToCreate.length)));
    }

    final arch = config.architecture;
    final di = arch?.di ?? 'get_it';
    final nav = arch?.navigation ?? 'go_router';
    final net = arch?.network ?? 'dio';
    
    yield ArchitectureEvent(message: 'Writing core tech stack files...', progress: 0.4);

    // 1. Dependency Injection (lib/core/di/injection_container.dart)
    String diContent = '';
    if (di == 'get_it' || di == 'injectable') {
      diContent = '''
import 'package:get_it/get_it.dart';

final sl = GetIt.instance; // Service Locator

Future<void> init() async {
  // Core
  // TODO: Register Network Client
  // TODO: Register Local Storage
  
  // Features
  // TODO: Register Data Sources
  // TODO: Register Repositories
  // TODO: Register Use Cases
  // TODO: Register State Management (BLoC/Cubit)
}
''';
    } else {
      diContent = '''
// Manual Dependency Injection setup
// Consider using a service locator pattern or passing dependencies explicitly.

Future<void> init() async {
  // Initialize core services here
}
''';
    }
    await File('${projectDir.path}/lib/core/di/injection_container.dart').writeAsString(diContent);

    // 2. Navigation (lib/core/router/app_router.dart)
    String routerContent = '';
    if (nav == 'go_router') {
      routerContent = '''
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final GoRouter appRouter = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const Scaffold(
        body: Center(child: Text('Home (Generated by FlutterForge)')),
      ),
    ),
  ],
);
''';
    } else if (nav == 'auto_route') {
      routerContent = '''
import 'package:auto_route/auto_route.dart';
part 'app_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Screen,Route')
class AppRouter extends _\$AppRouter {
  @override
  List<AutoRoute> get routes => [
    // AutoRoute(page: HomeRoute.page, initial: true),
  ];
}

final appRouter = AppRouter();
''';
    }
    if (routerContent.isNotEmpty) {
      await File('${projectDir.path}/lib/core/router/app_router.dart').writeAsString(routerContent);
    }

    // 3. Network (lib/core/network/api_client.dart)
    String networkContent = '';
    if (net == 'dio') {
      networkContent = '''
import 'package:dio/dio.dart';

class ApiClient {
  final Dio _dio;

  ApiClient() : _dio = Dio(BaseOptions(
    connectTimeout: const Duration(seconds: 10),
    receiveTimeout: const Duration(seconds: 10),
    headers: {'Content-Type': 'application/json'},
  )) {
    _dio.interceptors.add(LogInterceptor(responseBody: true));
  }

  Dio get dio => _dio;
}
''';
    } else {
      networkContent = '''
import 'package:http/http.dart' as http;

class ApiClient {
  final http.Client _client;

  ApiClient() : _client = http.Client();

  http.Client get client => _client;
}
''';
    }
    await File('${projectDir.path}/lib/core/network/api_client.dart').writeAsString(networkContent);

    // 4. Local Storage (lib/core/storage/storage_service.dart)
    final storage = arch?.localStorage ?? 'shared_prefs';
    String storageContent = '';
    if (storage == 'hive') {
      storageContent = '''
import 'package:hive_flutter/hive_flutter.dart';

class StorageService {
  static Future<void> init() async {
    await Hive.initFlutter();
  }
}
''';
    } else if (storage == 'isar') {
      storageContent = '''
import 'package:isar/isar.dart';

class StorageService {
  static late Isar isar;

  static Future<void> init() async {
    // isar = await Isar.open([...]);
  }
}
''';
    } else {
      storageContent = '''
import 'package:shared_preferences/shared_preferences.dart';

class StorageService {
  static late SharedPreferences prefs;

  static Future<void> init() async {
    prefs = await SharedPreferences.getInstance();
  }
}
''';
    }
    await File('${projectDir.path}/lib/core/storage/storage_service.dart').writeAsString(storageContent);

    // 4. Environment/Flavors (lib/core/env/app_config.dart)
    final env = config.environment;
    if (env.hasDev || env.hasStaging || env.hasProd) {
      final envContent = '''
enum Environment {
  dev,
  staging,
  prod,
}

class AppConfig {
  final Environment environment;
  final String apiBaseUrl;
  final String appName;

  AppConfig({
    required this.environment,
    required this.apiBaseUrl,
    required this.appName,
  });

  static late AppConfig _instance;
  static AppConfig get instance => _instance;

  static void instantiate({
    required Environment environment,
    required String apiBaseUrl,
    required String appName,
  }) {
    _instance = AppConfig(
      environment: environment,
      apiBaseUrl: apiBaseUrl,
      appName: appName,
    );
  }
  
  bool get isDev => environment == Environment.dev;
  bool get isStaging => environment == Environment.staging;
  bool get isProd => environment == Environment.prod;
}
''';
      await File('${projectDir.path}/lib/core/env/app_config.dart').writeAsString(envContent);
    }

    yield ArchitectureEvent(message: 'Writing lib/main.dart...', progress: 0.8);
    
    // Main.dart needs to incorporate DI initialization and Firebase if integrated
    final needsFirebase = config.integrations.firebaseAuth || config.integrations.firebaseFirestore || config.integrations.firebaseStorage;
    
    final mainDartContent = '''
import 'package:flutter/material.dart';
${needsFirebase ? "import 'package:firebase_core/firebase_core.dart';\n// TODO: Add firebase_options.dart" : ""}
import 'core/di/injection_container.dart' as di;
${nav == 'go_router' ? "import 'core/router/app_router.dart';" : ""}
${nav == 'auto_route' ? "import 'core/router/app_router.dart';" : ""}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  ${needsFirebase ? "await Firebase.initializeApp(); // TODO: Add DefaultFirebaseOptions.currentPlatform" : ""}
  
  await di.init();
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp${nav == 'go_router' ? ".router" : (nav == 'auto_route' ? ".router" : "")}(
      title: '${config.projectName}',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      ${nav == 'go_router' ? "routerConfig: appRouter," : ""}
      ${nav == 'auto_route' ? "routerConfig: appRouter.config()," : ""}
      ${nav != 'go_router' && nav != 'auto_route' ? "home: const Scaffold(body: Center(child: Text('FlutterForge Generated App')))," : ""}
    );
  }
}
''';

    await File('${projectDir.path}/lib/main.dart').writeAsString(mainDartContent);

    yield ArchitectureEvent(
      message: 'Architecture generated successfully.',
      level: 'success',
      progress: 1.0,
    );
  }
}
