import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import '../generated/protocol.dart';

class GithubPusherEvent {
  final String message;
  final String level;
  final double progress;
  final bool isError;

  GithubPusherEvent({
    required this.message,
    this.level = 'info',
    this.progress = 0.0,
    this.isError = false,
  });
}

class GithubPusher {
  Stream<GithubPusherEvent> push(ProjectConfig config) async* {
    if (config.githubToken == null || config.githubToken!.isEmpty) {
      yield GithubPusherEvent(
        message: 'No GitHub token provided. Skipping GitHub push.',
        level: 'warning',
        progress: 1.0,
      );
      return;
    }

    final token = config.githubToken!;
    final projectPath = '/tmp/flutterforge/${config.projectId}';
    final repoName = _slugify(config.projectName);

    yield GithubPusherEvent(
      message: 'Authenticating with GitHub...',
      level: 'info',
      progress: 0.1,
    );

    // 1. Get authenticated user
    String? username;
    try {
      final userRes = await http.get(
        Uri.parse('https://api.github.com/user'),
        headers: {
          'Authorization': 'token \$token',
          'Accept': 'application/vnd.github.v3+json',
        },
      );
      
      if (userRes.statusCode == 200) {
        final data = jsonDecode(userRes.body);
        username = data['login'];
      } else {
        yield GithubPusherEvent(
          message: 'GitHub authentication failed: \${userRes.statusCode} \${userRes.body}',
          level: 'error',
          progress: 0.1,
          isError: true,
        );
        return;
      }
    } catch (e) {
      yield GithubPusherEvent(
        message: 'GitHub API error: \$e',
        level: 'error',
        progress: 0.1,
        isError: true,
      );
      return;
    }

    yield GithubPusherEvent(
      message: 'Creating GitHub repository "\$repoName"...',
      level: 'info',
      progress: 0.3,
    );

    // 2. Create repo
    String? cloneUrl;
    try {
      final repoRes = await http.post(
        Uri.parse('https://api.github.com/user/repos'),
        headers: {
          'Authorization': 'token \$token',
          'Accept': 'application/vnd.github.v3+json',
        },
        body: jsonEncode({
          'name': repoName,
          'private': true,
          'description': 'Generated by FlutterForge',
        }),
      );

      if (repoRes.statusCode == 201) {
        final data = jsonDecode(repoRes.body);
        cloneUrl = data['clone_url'];
      } else if (repoRes.statusCode == 422) {
        // Repo might already exist, let's try to get it
        yield GithubPusherEvent(
          message: 'Repository might already exist, retrieving...',
          level: 'warning',
          progress: 0.4,
        );
        final getRepoRes = await http.get(
          Uri.parse('https://api.github.com/repos/\$username/\$repoName'),
          headers: {
            'Authorization': 'token \$token',
            'Accept': 'application/vnd.github.v3+json',
          },
        );
        if (getRepoRes.statusCode == 200) {
          final data = jsonDecode(getRepoRes.body);
          cloneUrl = data['clone_url'];
        } else {
          yield GithubPusherEvent(
            message: 'Failed to create or retrieve repository: \${repoRes.body}',
            level: 'error',
            progress: 0.4,
            isError: true,
          );
          return;
        }
      } else {
        yield GithubPusherEvent(
          message: 'Failed to create repository: \${repoRes.statusCode} \${repoRes.body}',
          level: 'error',
          progress: 0.4,
          isError: true,
        );
        return;
      }
    } catch (e) {
      yield GithubPusherEvent(
        message: 'Failed to create repository: \$e',
        level: 'error',
        progress: 0.4,
        isError: true,
      );
      return;
    }

    if (cloneUrl == null) {
      yield GithubPusherEvent(
        message: 'Could not resolve clone URL.',
        level: 'error',
        progress: 0.5,
        isError: true,
      );
      return;
    }

    // 3. Git Operations
    yield GithubPusherEvent(
      message: 'Initializing Git repository and pushing...',
      level: 'info',
      progress: 0.6,
    );

    // Insert token into the clone URL for authentication
    final authUrl = cloneUrl.replaceFirst('https://', 'https://oauth2:\$token@');

    try {
      await _runCommand('git', ['init'], projectPath);
      yield GithubPusherEvent(message: 'Git init done.', level: 'info', progress: 0.65);

      await _runCommand('git', ['branch', '-M', 'main'], projectPath);
      
      await _runCommand('git', ['add', '.'], projectPath);
      yield GithubPusherEvent(message: 'Added files to git.', level: 'info', progress: 0.7);

      await _runCommand('git', ['commit', '-m', 'Initial commit by FlutterForge'], projectPath);
      yield GithubPusherEvent(message: 'Committed files.', level: 'info', progress: 0.8);

      // It's possible origin already exists if we're retrying, so remove it first if needed, but since it's a fresh /tmp dir it should be fine.
      await _runCommand('git', ['remote', 'add', 'origin', authUrl], projectPath);
      
      yield GithubPusherEvent(message: 'Pushing to GitHub...', level: 'info', progress: 0.9);
      final pushRes = await Process.run('git', ['push', '-u', 'origin', 'main'], workingDirectory: projectPath);
      
      if (pushRes.exitCode != 0) {
        yield GithubPusherEvent(
          message: 'Failed to push to GitHub: \${pushRes.stderr}',
          level: 'error',
          progress: 0.9,
          isError: true,
        );
        return;
      }

      yield GithubPusherEvent(
        message: 'Successfully pushed to GitHub: https://github.com/\$username/\$repoName',
        level: 'success',
        progress: 1.0,
      );

    } catch (e) {
      yield GithubPusherEvent(
        message: 'Git operation failed: \$e',
        level: 'error',
        progress: 0.9,
        isError: true,
      );
    }
  }

  Future<void> _runCommand(String executable, List<String> arguments, String workingDirectory) async {
    final result = await Process.run(executable, arguments, workingDirectory: workingDirectory);
    if (result.exitCode != 0) {
      throw Exception('Command failed: \$executable \${arguments.join(' ')}\\n\${result.stderr}');
    }
  }

  String _slugify(String text) {
    return text.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '-').replaceAll(RegExp(r'^-+|-+\$'), '');
  }
}
